# Generated by Django 5.1.1 on 2024-12-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.theater')),
            ],
        ),
    ]
