# Generated by Django 5.1.1 on 2024-12-27 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_showtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_tickets', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.movie')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.showtime')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.theater')),
            ],
        ),
    ]
