# Generated by Django 5.1.1 on 2025-01-06 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_theater_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='event_app.theater'),
        ),
    ]
